"""Revision ID: 21ac01d9ca35
Revises: 9b3af360a545
Create Date: 2025-11-10 15:27:49.416695
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ac01d9ca35'
down_revision = "faff471948d3"
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
