import { ExplanationResponse } from "@/types/explanations";
import { getClientUserId } from "@/lib/user";
import { apiFetch } from "./client";
import { DEMO_MODE } from "@/config/demo";

export async function generateExplanation(text: string, mode: string = "auto"): Promise<ExplanationResponse> {
  if (DEMO_MODE) {
    return Promise.resolve({
      chosen_style: "step_by_step",
      blocks: [
        {
          style: "step_by_step",
          title: "Quick breakdown (demo)",
          content: `1) You asked: ${text.slice(0, 120)}...\n2) In demo mode we skip the backend and show a plausible outline.\n3) Each bullet would normally be generated by the model.`,
        },
        {
          style: "big_picture",
          title: "Big picture",
          content: "Focus on the core idea, then one concrete example, and finally how to verify your understanding.",
        },
      ],
    });
  }
  return apiFetch<ExplanationResponse>("/explanations/generate", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-User-Id": getClientUserId(),
    },
    body: JSON.stringify({ text, mode }),
  });
}
